"""update user

Revision ID: 2e1bd4b70186
Revises: 482f101b5836
Create Date: 2025-06-08 15:03:09.099087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1bd4b70186'
down_revision: Union[str, None] = '482f101b5836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_user', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('role_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role_admin')
    op.drop_column('users', 'role_user')
    # ### end Alembic commands ###
